[package]
name = "kanjidic_server"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [ "json" ] }
mongodb = "2.0.0-beta.3"
futures = "0.3"
kanjidic_types = { path = "../kanjidic_types"}
serde = { version = "1.0", features = ["derive"] }