[package]
name = "kanjidic_types"
version = "0.1.0"
edition = "2018"

[dependencies]
isolang = { git = "https://github.com/humenda/isolang-rs", branch = "master", features = [ "serde_serialize" ] }
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }