[package]
name = "kanjidic_parser"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1.0.35"
roxmltree = "0.15.0"
nom = "7.1.1"
kanjidic_types = "0.1.1"
serde = { version = "1.0.144", features = ["derive"] }
kradical_static = "0.2.0"

[dev-dependencies]
lazy_static = "1.4"