[package]
name = "kanjidic_parser"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1"
roxmltree = "0.14"
nom = "6"
iso639-1 = "0.3"
num_enum = "0.5"

[dev-dependencies]
lazy_static = "1.4"