[package]
name = "kanjidic_parser"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1"
roxmltree = "0.14"
nom = "6"
num_enum = "0.5"
isolang = { git = "https://github.com/humenda/isolang-rs", branch = "master" }


[dev-dependencies]
lazy_static = "1.4"