[package]
name = "kanjidic_converter"
version = "0.1.0"
edition = "2018"

[dependencies]
kanjidic_parser = { path = "../kanjidic_parser"}
thiserror = "1.0.35"
serde_json = "1.0.85"
clap = { version = "3.2.22", features = ["derive"] }