[package]
name = "kanjidic_database_populator"
version = "0.1.0"
edition = "2018"

[dependencies]
mongodb = "2.0.0-beta.2"
kanjidic_parser = { path = "../kanjidic_parser"}
serde_json = "1.0"
tokio = "1"